source 'https://rubygems.org'
ruby '2.6.4'
gem 'amazon-ecs'
gem 'crowi-client', git: 'https://github.com/pooza/crowi-client.git'
gem 'dropbox-sdk-v2', git: 'https://github.com/pooza/dropbox-sdk-ruby.git'
gem 'dry-validation'
gem 'fastimage'
gem 'ginseng-core', git: 'https://github.com/pooza/ginseng-core.git'
gem 'ginseng-postgres', git: 'https://github.com/pooza/ginseng-postgres.git'
gem 'ginseng-web', git: 'https://github.com/pooza/ginseng-web.git'
gem 'mimemagic'
gem 'nokogiri'
gem 'rails-erb-lint'
gem 'redis'
gem 'rspotify'
gem 'rubocop'
gem 'sanitize'
gem 'sidekiq'
gem 'sidekiq-scheduler'
gem 'unicode'
