source 'https://rubygems.org'
gem 'activesupport'
gem 'addressable'
gem 'amazon-ecs'
gem 'httparty'
gem 'nokogiri'
gem 'rake'
gem 'rest-client'
gem 'rspotify', github: 'pooza/rspotify'
gem 'sinatra'
gem 'syslog-logger'
gem 'test-unit'
gem 'thin'
