source 'https://rubygems.org'
ruby '2.7.0'
gem 'bootsnap'
gem 'crowi-client', github: 'pooza/crowi-client'
gem 'dropbox_api'
gem 'dry-validation'
gem 'fastimage'
gem 'ginseng-core', github: 'pooza/ginseng-core'
gem 'ginseng-postgres', github: 'pooza/ginseng-postgres'
gem 'ginseng-web', github: 'pooza/ginseng-web'
gem 'mimemagic'
gem 'nokogiri'
gem 'rails-erb-lint'
gem 'redis'
gem 'rspotify'
gem 'sanitize'
gem 'sidekiq'
gem 'sidekiq-scheduler'
gem 'slim'
gem 'vacuum'
