properties:
  attachment:
    properties:
      types:
        properties:
          animation_image:
            type: string
          audio:
            type: string
          image:
            type: string
          video:
            type: string
        type: object
    type: object
  status:
    properties:
      label:
        type: string
      spoiler_text:
        type: string
    type: object
  streaming:
    properties:
      root_cert_file:
        type: string
      verify_peer:
        type: boolean
    type: object
  theme:
    properties:
      color:
        type: string
    type: object
  url:
    format: uri
    type: string
required:
  - url
type: object
