#!/bin/sh

# PROVIDE: mulukhiya_puma
# REQUIRE: LOGIN redis

# Add the following line to /etc/rc.conf to enable `mulukhiya':
#
#mulukhiya_enable="YES"

. /etc/rc.subr

name="mulukhiya_puma"
rcvar="mulukhiya_enable"

load_rc_config "$name"
: ${mulukhiya_enable="NO"}
: ${mulukhiya_path=""}
: ${mulukhiya_user=""}

export PATH=${PATH}:/usr/local/bin:/usr/local/sbin
export LANG=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF-8

start_cmd=${name}_start
stop_cmd=${name}_stop

# ⚠ puma も proctitle を "ruby: puma <version> (tcp://...) [mulukhiya-toot-proxy]"
# へ書き換えるので、'puma_daemon.rb' だけでは一致しない (#4675)。cluster 時の
# ワーカーは "puma: cluster worker ..." なので、区切りに [ :] を許している。
# ⚠ 同じユーザーで動く Mastodon 側の puma を巻き込まないよう、必ず
# mulukhiya-toot-proxy まで含めて絞ること。
mulukhiya_puma_pattern='puma_daemon\.rb|puma[ :].*mulukhiya-toot-proxy'
mulukhiya_puma_kill_wait=20

mulukhiya_puma_start() {
  cd $mulukhiya_path
  sudo -u $mulukhiya_user /usr/sbin/daemon \
    /usr/local/bin/bash -lc "cd ${mulukhiya_path} && RACK_ENV=production bundle exec bin/puma_daemon.rb start"
}

mulukhiya_puma_stop() {
  cd $mulukhiya_path
  sudo -u $mulukhiya_user /usr/local/bin/bash -lc 'bundle exec bin/puma_daemon.rb stop' 2>/dev/null
  # pid ファイルから辿れない取り残しにも TERM を送る (#4675)。
  pkill -u $mulukhiya_user -f "$mulukhiya_puma_pattern" 2>/dev/null
  # ⚠ SIGKILL の前に落ちきるのを待つ。待たずに -9 を撃つと、graceful stop の
  # 直後に in-flight の処理を毎回強制終了することになる。
  _i=0
  while [ $_i -lt $mulukhiya_puma_kill_wait ]; do
    pgrep -u $mulukhiya_user -f "$mulukhiya_puma_pattern" >/dev/null 2>&1 || return 0
    sleep 1
    _i=$((_i + 1))
  done
  pkill -9 -u $mulukhiya_user -f "$mulukhiya_puma_pattern" 2>/dev/null
  sleep 2
}

run_rc_command "$1"
