#!/bin/sh

# PROVIDE: mulukhiya_sidekiq
# REQUIRE: LOGIN redis

# Add the following line to /etc/rc.conf to enable `mulukhiya':
#
#mulukhiya_enable="YES"

. /etc/rc.subr

name="mulukhiya_sidekiq"
rcvar="mulukhiya_enable"

load_rc_config "$name"
: ${mulukhiya_enable="NO"}
: ${mulukhiya_path=""}
: ${mulukhiya_user=""}

export PATH=${PATH}:/usr/local/bin:/usr/local/sbin
export LANG=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF-8

start_cmd=${name}_start
stop_cmd=${name}_stop

# ⚠ sidekiq は proctitle を "ruby: sidekiq <version> mulukhiya-toot-proxy ..." へ
# 書き換えるので、'sidekiq_daemon.rb' だけでは一致しない。この保険は導入以来ずっと
# 空振りしており、pid ファイルから辿れない 2 本目を落とせなかった (#4675)。
# ⚠ 同じユーザーで動く Mastodon 側の sidekiq (proctitle は "sidekiq <version>
# mastodon") を巻き込まないよう、必ず mulukhiya-toot-proxy まで含めて絞ること。
mulukhiya_sidekiq_pattern='sidekiq_daemon\.rb|sidekiq .*mulukhiya-toot-proxy'
mulukhiya_sidekiq_kill_wait=20

mulukhiya_sidekiq_start() {
  cd $mulukhiya_path
  sudo -u $mulukhiya_user /usr/sbin/daemon \
    /usr/local/bin/bash -lc "cd ${mulukhiya_path} && bundle exec bin/sidekiq_daemon.rb start"
}

mulukhiya_sidekiq_stop() {
  cd $mulukhiya_path
  sudo -u $mulukhiya_user /usr/local/bin/bash -lc 'bundle exec bin/sidekiq_daemon.rb stop' 2>/dev/null
  # pid ファイルから辿れない取り残しにも TERM を送る (#4675)。
  pkill -u $mulukhiya_user -f "$mulukhiya_sidekiq_pattern" 2>/dev/null
  # ⚠ SIGKILL の前に落ちきるのを待つ。待たずに -9 を撃つと、graceful stop の
  # 直後に in-flight の処理を毎回強制終了することになる。
  _i=0
  while [ $_i -lt $mulukhiya_sidekiq_kill_wait ]; do
    pgrep -u $mulukhiya_user -f "$mulukhiya_sidekiq_pattern" >/dev/null 2>&1 || return 0
    sleep 1
    _i=$((_i + 1))
  done
  pkill -9 -u $mulukhiya_user -f "$mulukhiya_sidekiq_pattern" 2>/dev/null
  sleep 2
}

run_rc_command "$1"
