#!/bin/sh

# PROVIDE: mulukhiya_listener
# REQUIRE: LOGIN

# Add the following line to /etc/rc.conf to enable `mulukhiya':
#
#mulukhiya_enable="YES"

. /etc/rc.subr

name="mulukhiya_listener"
rcvar="mulukhiya_enable"

load_rc_config "$name"
: ${mulukhiya_enable="NO"}
: ${mulukhiya_path=""}
: ${mulukhiya_user=""}

export PATH=${PATH}:/usr/local/bin:/usr/local/sbin
export LANG=ja_JP.UTF-8
export LC_ALL=ja_JP.UTF-8

start_cmd=${name}_start
stop_cmd=${name}_stop

mulukhiya_listener_start() {
  cd $mulukhiya_path
  sudo -u $mulukhiya_user zsh -c 'bundle exec rake mulukhiya:listener:start'
}

mulukhiya_listener_stop() {
  cd $mulukhiya_path
  sudo -u $mulukhiya_user zsh -c 'bundle exec rake mulukhiya:listener:stop'
}

run_rc_command "$1"
