controller: mastodon
crypt:
  password: your_password
environment: production
handler:
  default_tag:
    tags:
      - your_default_hash_tag
mastodon:
  url: https://mstdn.example.com/
postgres:
  dsn: postgres://postgres:password@localhost:5432/mastodon
sidekiq:
  auth:
    password: your_password
