agent:
  info:
    token: your_token
  test:
    token: your_token
controller: pleroma
crypt:
  password: your_password
  salt: your_salt
environment: production
handler:
  default_tag:
    tags:
      - タグ1
      - タグ2
  image_resize:
    pixel: 1920
  reply_reaction:
    disable: true
  slack_alert:
    hooks:
      - https://hooks.slack.com/services/xxxxx
      - https://discordapp.com/api/webhooks/xxxxx/slack
pleroma:
  attachment:
    types:
      image: image/jpeg
  url: https://pleroma.example.com/
postgres:
  dsn: postgres://pleroma@localhost:5432/pleroma
sidekiq:
  auth:
    password: your_password
  redis:
    dsn: redis://localhost:6379/2
user_config:
  redis:
    dsn: redis://localhost:6379/1
