controller: pleroma
crypt:
  password: your_password
environment: production
handler:
  default_tag:
    tags:
      - your_default_hash_tag
  reply_reaction:
    disable: true
pleroma:
  url: https://pleroma.example.com/
postgres:
  dsn: postgres://pleroma:password@localhost:5432/pleroma
sidekiq:
  auth:
    password: your_password
