agent:
  info:
    token: your_token
  test:
    token: your_token
controller: meisskey
crypt:
  password: your_password
  salt: your_salt
environment: production
handler:
  default_tag:
    tags:
      - タグ1
      - タグ2
  image_resize:
    pixel: 1920
meisskey:
  attachment:
    types:
      image: image/jpeg
  url: https://meisskey.example.com/
mongo:
  dsn: mongo://localhost:27017/misskey
sidekiq:
  auth:
    password: your_password
  redis:
    dsn: redis://localhost:6379/2
user_config:
  redis:
    dsn: redis://localhost:6379/1
