agent:
  info:
    token: your_token
  test:
    token: your_token
crypt:
  password: your_password
  salt: your_salt
environment: production
handler:
  default_tag:
    tags:
      - タグ1
      - タグ2
  image_resize:
    pixel: 1920
  slack_alert:
    hooks:
      - https://hooks.slack.com/services/xxxxx
      - https://discordapp.com/api/webhooks/xxxxx/slack
mastodon:
  search:
    limit: 100
  url: https://mstdn.example.com/
postgres:
  dsn: postgres://postgres@localhost:5432/mastodon
sidekiq:
  auth:
    password: your_password
  redis:
    dsn: redis://localhost:6379/2
  schedule:
    announcement:
      every: 10m
user_config:
  redis:
    dsn: redis://localhost:6379/1
