controller: meisskey
crypt:
  password: your_password
environment: production
handler:
  default_tag:
    tags:
      - your_default_hash_tag
  reply_reaction:
    disable: true
meisskey:
  url: https://meisskey.example.com/
mongo:
  dsn: mongo://localhost:27017/misskey
sidekiq:
  auth:
    password: your_password
