controller: pleroma
crypt:
  password: your_password
environment: production
handler:
  default_tag:
    tags:
      - your_default_hash_tag
  image_format_convert:
    gif: false
pleroma:
  url: https://pleroma.example.com/
postgres:
  dsn: postgres://pleroma:password@localhost:5432/pleroma
sidekiq:
  auth:
    password: your_password
