name: 🐛 バグ報告
description: バグ報告
labels: ["bug"]

body:
  - type: markdown
    attributes:
      label: 概要
    validations:
      required: true

  - type: markdown
    attributes:
      label: 現象
    validations:
      required: true

  - type: markdown
    attributes:
      label: 期待される動作
    validations:
      required: true

  - type: markdown
    attributes:
      label: 再現手順
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: markdown
    attributes:
      label: 環境
    validations:
      required: true
