name: バグ報告
description: バグの報告
labels: ["bug"]

body:
  - type: textarea
    attributes:
      label: 現象
      description: 何が起きたかを記述してください。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 期待される動作
      description: 本来どう動くべきかを記述してください。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 再現手順
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false

  - type: dropdown
    attributes:
      label: SNS種別
      options:
        - Mastodon
        - Misskey
    validations:
      required: true

  - type: input
    attributes:
      label: モロヘイヤのバージョン
      placeholder: "5.2.0"
    validations:
      required: false

  - type: textarea
    attributes:
      label: 補足
      description: ログ、スクリーンショットなど。
    validations:
      required: false
