agent:
  info:
    token: your_token
  test:
    token: your_token
alert:
  hooks:
    - https://hooks.slack.com/services/xxxxx
    - https://discordapp.com/api/webhooks/xxxxx/slack
controller: misskey
crypt:
  password: your_password
  salt: your_salt
environment: production
handler:
  hexo_announce:
    category: お知らせ
  image_resize:
    pixel: 1920
  itunes_image:
    disable: true
  spotify_image:
    disable: true
  you_tube_image:
    disable: true
misskey:
  attachment:
    types:
      image: image/jpeg
  url: https://misskey.example.com/
postgres:
  dsn: postgres://misskey@localhost:5432/misskey
sidekiq:
  auth:
    password: your_password
  redis:
    dsn: redis://localhost:6379/2
tagging:
  default_tags:
    - デフォルトタグ1
    - デフォルトタグ2
  dictionaries: []
user_config:
  redis:
    dsn: redis://localhost:6379/1
