environment: production
controller: misskey
misskey:
  url: https://misskey.example.com/
  attachment:
    types:
      image: image/jpeg
agent:
  test:
    token: 'your_token'
  info:
    token: 'your_token'
postgres:
  dsn: postgres://misskey@localhost:5432/misskey
user_config:
  redis:
    dsn: redis://localhost:6379/1
sidekiq:
  redis:
    dsn: redis://localhost:6379/2
  auth:
    password: your_password
alert:
  hooks:
    - https://hooks.slack.com/services/xxxxx
    - https://discordapp.com/api/webhooks/xxxxx/slack
tagging:
  default_tags:
    - デフォルトタグ1
    - デフォルトタグ2
  dictionaries:
    - url: https://mstdn.example.com/dictionaries/dic1
      fields:
        - field1
        - field2
    - url: https://mstdn.example.com/dictionaries/dic2
      type: relative
    - url: https://mstdn.example.com/dictionaries/dic3
      type: mecab
feed:
  custom:
    - path: sample/foo
      command:
        - bin/sample/custom_feed_1.sh
      title: タイトル1
      description: 説明1
    - path: sample/bar
      command:
        - bin/sample/custom_feed_2.sh
      title: タイトル2
      description: 説明2
api:
  custom:
    - path: sample/foo
      command:
        - bin/sample/custom_api_1.sh
    - path: sample/bar
      command:
        - bin/sample/custom_api_2.sh
crypt:
  salt: your_salt
  password: your_password
