agent:
  info:
    token: your_token
  test:
    token: your_token
alert:
  hooks:
    - https://hooks.slack.com/services/xxxxx
    - https://discordapp.com/api/webhooks/xxxxx/slack
crypt:
  password: your_password
  salt: your_salt
environment: production
handler:
  default_tag:
    tags:
      - タグ1
      - タグ2
  dictionary_tag:
    dics: []
  hexo_announce:
    category: お知らせ
  image_resize:
    pixel: 1920
  itunes_image:
    disable: true
  spotify_image:
    disable: true
  you_tube_image:
    disable: true
mastodon:
  search:
    limit: 100
  url: https://mstdn.example.com/
postgres:
  dsn: postgres://postgres@localhost:5432/mastodon
sidekiq:
  auth:
    password: your_password
  redis:
    dsn: redis://localhost:6379/2
  schedule:
    announcement:
      every: 10m
user_config:
  redis:
    dsn: redis://localhost:6379/1
webui:
  media:
    copyright:
      message: 画像の著作権について
      url: https://blog.example.com/copyright
