agent:
  info:
    token: your_token
  test:
    token: your_token
alert:
  hooks:
    - https://hooks.slack.com/services/xxxxx
    - https://discordapp.com/api/webhooks/xxxxx/slack
api:
  custom:
    - command:
        - bin/sample/custom_api_1.sh
      path: sample/foo
    - command:
        - bin/sample/custom_api_2.sh
      path: sample/bar
controller: misskey
crypt:
  password: your_password
  salt: your_salt
environment: production
feed:
  custom:
    - command:
        - bin/sample/custom_feed_1.sh
      description: 説明1
      path: sample/foo
      title: タイトル1
    - command:
        - bin/sample/custom_feed_2.sh
      description: 説明2
      path: sample/bar
      title: タイトル2
misskey:
  attachment:
    types:
      image: image/jpeg
  url: https://misskey.example.com/
postgres:
  dsn: postgres://misskey@localhost:5432/misskey
sidekiq:
  auth:
    password: your_password
  redis:
    dsn: redis://localhost:6379/2
tagging:
  default_tags:
    - デフォルトタグ1
    - デフォルトタグ2
  dictionaries:
    - fields:
        - field1
        - field2
      url: https://mstdn.example.com/dictionaries/dic1
    - type: relative
      url: https://mstdn.example.com/dictionaries/dic2
    - type: mecab
      url: https://mstdn.example.com/dictionaries/dic3
user_config:
  redis:
    dsn: redis://localhost:6379/1