type: object
properties:
  disabled:
    type: boolean
  timeout:
    type: integer
  ignore:
    type: object
    properties:
      domains:
        type: array
        items:
          type: string
    required:
      - domains
