properties:
  disabled:
    type: boolean
  ignore:
    properties:
      domains:
        items:
          format: hostname
          type: string
        type: array
    required:
      - domains
    type: object
  timeout:
    minimum: 1
    type: integer
type: object
