properties:
  category:
    type: string
  comments:
    type: boolean
  dir:
    type: string
  disabled:
    type: boolean
  path:
    type: string
  timeout:
    minimum: 1
    type: integer
type: object
