properties:
  disabled:
    type: boolean
  message:
    type: string
  tag:
    type: string
  timeout:
    type: integer
  url:
    format: uri
    type: string
required:
  - tag
  - url
type: object
