label: iTunes画像取得
description: iTunes URLからアートワーク画像を取得して添付します
properties:
  disabled:
    type: boolean
  pixel:
    minimum: 200
    type: integer
  timeout:
    minimum: 1
    type: integer
type: object
