properties:
  disabled:
    type: boolean
  tags:
    properties:
      audio:
        type: string
      image:
        type: string
      video:
        type: string
    type: object
  timeout:
    minimum: 1
    type: integer
type: object
