type: object
properties:
  disabled:
    type: boolean
  timeout:
    type: integer
  tags:
    type: object
    properties:
      audio:
        type: string
      image:
        type: string
      video:
        type: string
