properties:
  services:
    type: array
    items:
      type: object
      properties:
        pattern:
          type: string
        tags:
          type: array
          items:
            type: string
        url:
          type: string
          format: uri
required:
  - services
