properties:
  disabled:
    type: boolean
  services:
    items:
      properties:
        pattern:
          format: regex
          type: string
        tags:
          items:
            type: string
          type: array
        url:
          format: uri
          type: string
      type: object
    type: array
  timeout:
    minimum: 1
    type: integer
required:
  - services
type: object
