properties:
  disabled:
    type: boolean
  tags:
    properties:
      rules:
        items:
          properties:
            removal_tags:
              items:
                type: string
              type: array
            search:
              type: string
          type: object
        type: array
    type: object
  timeout:
    minimum: 1
    type: integer
type: object