label: 短縮URL展開
description: 短縮URLをリダイレクト先の元URLに展開します
properties:
  disabled:
    type: boolean
  domains:
    items:
      type: string
    type: array
  timeout:
    minimum: 1
    type: integer
type: object
