module Mulukhiya
  class VideoURI < Ginseng::YouTube::URI
    include Package

    def artist
      artist = data.dig('snippet', 'tags')&.first if auto_generated_description?
      artist ||= channel.sub(/ - Topic$/, '') if music?
      artist ||= channel
      return artist
    end

    def auto_generated_description?
      return data.dig('snippet', 'description').end_with?('Auto-generated by YouTube.')
    end
  end
end
