ja:
  dry_validation:
    errors:
      array?: 配列ではありません。
      bool?: 真偽値ではありません。
      gt?: 値が小さすぎます。
      hash?: ハッシュではありません。
      int?: 数値ではありません。
      key?: 空欄です。
      lt?: 値が大きすぎます。
      str?: 文字列ではありません。