- class: Mulukhiya::NodeinfoController
  path: /nodeinfo
- class: Mulukhiya::UIController
  path: /mulukhiya
- class: Mulukhiya::APIController
  path: /mulukhiya/api
- class: Mulukhiya::FeedController
  path: /mulukhiya/feed
- class: Mulukhiya::WebhookController
  path: /mulukhiya/webhook
- class: Sidekiq::Web
  path: /mulukhiya/sidekiq
